"""new tables

Revision ID: 128ae4d1ca42
Revises: 
Create Date: 2018-09-21 22:49:19.643511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128ae4d1ca42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
